export const PERMISSION_CATALOG = {
  TENANT: ["TENANT_VIEW", "TENANT_UPDATE", "TENANT_SUSPEND", "TENANT_ACTIVATE"],
  DEPARTMENT: ["DEPARTMENT_VIEW", "DEPARTMENT_CREATE", "DEPARTMENT_UPDATE", "DEPARTMENT_DELETE"],
  STAFF: ["STAFF_VIEW", "STAFF_CREATE", "STAFF_UPDATE", "STAFF_DEACTIVATE", "STAFF_INVITE"],
  ROLE: ["ROLE_VIEW", "ROLE_CREATE", "ROLE_UPDATE", "ROLE_DELETE"],
  PATIENT: ["PATIENT_VIEW", "PATIENT_CREATE", "PATIENT_UPDATE", "PATIENT_EXPORT", "PATIENT_VIEW_DIAGNOSIS", "PATIENT_VIEW_NOTES"],
  APPOINTMENT: ["APPOINTMENT_VIEW", "APPOINTMENT_CREATE", "APPOINTMENT_UPDATE", "APPOINTMENT_CANCEL"],
  VISIT: ["VISIT_VIEW", "VISIT_CREATE", "VISIT_UPDATE", "VISIT_FINALIZE"],
  PRESCRIPTION: ["PRESCRIPTION_VIEW", "PRESCRIPTION_CREATE", "PRESCRIPTION_UPDATE", "PRESCRIPTION_EXPORT"],
  MEDICINE: ["MEDICINE_VIEW", "MEDICINE_CREATE", "MEDICINE_UPDATE"],
  LAB: ["LAB_VIEW", "LAB_CREATE", "LAB_UPDATE"],
  DOCUMENT: ["DOCUMENT_VIEW", "DOCUMENT_UPLOAD", "DOCUMENT_DOWNLOAD"],
  BILLING: ["BILLING_VIEW", "BILLING_CREATE", "BILLING_UPDATE"],
  AUDIT: ["AUDIT_VIEW"],
  NOTIFICATION: ["NOTIFICATION_VIEW", "NOTIFICATION_MANAGE"],
  SEARCH: ["SEARCH_QUERY", "SEARCH_EXPORT"],
  DASHBOARD: ["DASHBOARD_VIEW"],
} as const;

export type PermissionCode = (typeof PERMISSION_CATALOG)[keyof typeof PERMISSION_CATALOG][number];

export const ALL_PERMISSIONS = Object.values(PERMISSION_CATALOG).flat() as string[];
